CREATE TABLE t_inventory (
    id bigint generated BY DEFAULT AS IDENTITY,
    sku_code VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id)
)