CREATE TABLE t_orders (
    id bigint generated BY DEFAULT AS IDENTITY,
    order_number VARCHAR(255) NOT NULL UNIQUE,
    sku_code VARCHAR(255) NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    order_status VARCHAR(255) NOT NULL CHECK (order_status IN ('PLACED', 'SHIPPED', 'DELIVERED')),
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
)