spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/product-service?authSource=admin
      auto-index-creation: true

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb:
      core.MongoTemplate: DEBUG

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints.web.exposure.include: health, info, metrics, prometheus
  metrics.distribution.percentiles-histogram.http.server.requests: true
  observations.key-values.application: product-service
  tracing.sampling.probability: 1.0