spring:
  application:
    name: inventory-service

  datasource:
    url: "jdbc:postgresql://localhost:5433/inventory-service?currentSchema=public"
    username: admin
    password: password

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: false

server:
  port: 8082

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs